# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 39d1959d0d91bdce0c779b4e588362f4b6a2ebf30b368a3d3fc6e5fa044f073a05cb0e26037a7d93e33fc3b9807515a6984b2034538cd3944810af575e5ccb61

test:
  secret_key_base: fe4c7eddf9a6cf13b78edac09ea0035577c643941cbfa8d601a423576b6a4325a911aa4cc056bbd4a6c7be5dddeae89f946d447db88a967bbe8f96f73408110d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
